FROM awbul/docker-sge:latest
RUN apt-get update -y && apt-get install -y git gfortran build-essential xorg-dev libreadline6 \
                                            libreadline6-dev maven liblzma-dev libcurl4-openssl-dev libpcre++-dev
WORKDIR /
RUN wget http://cran.r-project.org/src/base/R-3/R-3.5.0.tar.gz && \
    tar -xzf R-3.5.0.tar.gz && \
    cd /R-3.5.0 && \
    ./configure --enable-R-shlib && \
    make && \
    make install

echo export PATH=/R-3.5.0:$PATH >> /etc/bashrc

ADD install_packages.R /tmp/install_packages.R
RUN Rscript /tmp/install_packages.R

# docker run --rm -it -v ~/Documents/Projects/PrOType/:/PrOType/ protype:latest bash