---
output:
  word_document:
    reference_docx: styles.docx
params:
  outputDir: outputDir
---

# C.5 Genes in the classifier

```{r setup_C05, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	results = "asis"
)
```

```{r load_C05}
# Load packages, helpers, input data
suppressPackageStartupMessages({
  library(ggraph)
  library(here)
})
source(here("pipeline/7-supplementary/utils.R"))
source(here("pipeline/7-supplementary/utils-pathway.R"))

n_genes <- 55
grm <- "CTHRC1"

pdat_raw <- readr::read_csv(here("data/supp/boxplotorder.csv"),
                            col_types = readr::cols())
raw_ns <- load_nanostring()
arl_samples <- readxl::read_excel(here("data/nstring/Nanostring_ARL-all samples-all gnes_20180607.xlsx"))
sum_freq <- readr::read_csv(file.path(params$outputDir, "gene_selection/sum_freq/overall_freq.csv"),
                            col_types = readr::cols())
final_preds <- readr::read_csv(file.path(params$outputDir, "gene_selection/final_model/Final_Predictions.csv"),
                               col_types = list("X1" = readr::col_skip()))
aa_raw <- readRDS(file.path(
  params$outputDir,
  "unsupervised/map_genes/ov.afc1_xpn/npcp-hcNorm_ov.afc1_xpn.rds"
))
aa_clusts <- readRDS(file.path(
  params$outputDir,
  "unsupervised/final/ov.afc1_xpn/all_clusts_ov.afc1_xpn.rds"
)) %>%
  purrr::pluck("kmodes")
load(here("data/nstring/tcga_data_with_molsubtypes.rda")) # eset
mapped_tcga <- readr::read_csv(here("data/nstring/TCGA_sampleIDs_OTTA-Mapped.csv"), col_types = readr::cols())

fig_path <- file.path(params$outputDir, "supplementary/figures/C05")
```

## Network Diagrams

```{r pathway_munge}
# Munge to needed format
pdat <- pdat_raw %>% 
  tidyr::gather(key = subtype, value = edge, dplyr::matches(".+path.+")) %>%
  dplyr::mutate_at("subtype", forcats::fct_inorder) %>% 
  dplyr::filter(edge == "1") %>% 
  dplyr::select(-Obs, -edge)
```

```{r pathway_object}
# Pathway object for graphing
pdat_graph <- pdat %>% 
  tidyr::separate(col = subtype, into = c("subtype", "direction"), sep = "path")
g <- create_tbl_graph(
  data = pdat_graph,
  node = "path",
  edge = "gene",
  groups = list("subtype", "direction")
)
```

### Combined Pathways

```{r pathways_graph_combined, fig.width=8, fig.height=10}
set.seed(1)
gg_combined <- create_ggraph(
  graph = g,
  color = "subtype",
  linetype = "direction",
  title = "Gene Pathways"
)
# print(gg_combined)
ggsave(file.path(fig_path, "pathways_graph_combined.pdf"), gg_combined,
       width = 8, height = 10)
```

### Pathways by Subtype

```{r pathways_graph_by_subtype, fig.width=8, fig.height=10}
set.seed(1)
gg_subtype <- create_ggraph(
  graph = g,
  color = "subtype",
  linetype = "direction",
  title = "Gene Pathways by Subtype",
  facet = "subtype"
)
# print(gg_subtype)
ggsave(file.path(fig_path, "pathways_graph_by_subtype.pdf"), gg_subtype,
       width = 8, height = 10)
```

### Pathways by Direction

```{r pathways_graph_by_direction, fig.width=8, fig.height=10}
set.seed(1)
gg_direction <- create_ggraph(
  graph = g,
  color = "subtype",
  linetype = "direction",
  title = "Gene Pathways by Direction",
  facet = "direction"
)
# print(gg_direction)
ggsave(file.path(fig_path, "pathways_graph_by_direction.pdf"), gg_direction,
       width = 8, height = 10)
```

### Heatmap

```{r pathway_heatmap, fig.width=8, fig.height=7}
hm_pdat <- pdat %>% 
  dplyr::count(gene, subtype) %>% 
  tidyr::complete(gene, subtype, fill = list(n = 0)) %>%
  tidyr::spread(gene, n) %>% 
  as.data.frame() %>% 
  tibble::column_to_rownames("subtype")

hm_ga <- pheatmap::pheatmap(
  hm_pdat,
  fontsize_row = 5,
  fontsize_col = 6,
  main = "Gene Pathways Heatmap"
)
ggsave(here(fig_path, "pathways_heatmap.pdf"), hm_ga, width = 8, height = 7)

gene_order <- hm_ga %>% 
  purrr::pluck("tree_col") %>% 
  magrittr::extract(c("labels", "order")) %>% 
  purrr::invoke(magrittr::extract, .)
```

## C.6 Gene Expression Distribution on Top Genes

```{r final_glist}
# Final gene list
final_glist <- sum_freq %>%
  dplyr::arrange(dplyr::desc(rfFreq), dplyr::desc(lassoFreq)) %>%
  dplyr::pull(genes) %>%
  make.names() %>%
  purrr::discard(~ . %in% grm) %>%
  head(n_genes)

# Ordered by pathway clustering
final_glist_ordered <- gene_order %>%
  match(final_glist) %>%
  c(setdiff(seq_along(final_glist), .)) %>%
  magrittr::extract(final_glist, .)
```

### All-Array

```{r gene_ex_aa, fig.width=11, fig.height=11}
# Joined data (all-array)
aa_dat <- aa_raw %>%
  dplyr::select(final_glist_ordered) %>%
  tibble::rownames_to_column("sample") %>%
  tibble::add_column(Subtype = factor(dplyr::case_when(
    aa_clusts == 1 ~ "C2.IMM",
    aa_clusts == 2 ~ "C4.DIF",
    aa_clusts == 3 ~ "C5.PRO",
    aa_clusts == 4 ~ "C1.MES"
  )), .after = 1) %>%
  tidyr::gather(key = Gene, value = Expression, -c(1:2), factor_key = TRUE) %>%
  tibble::as_tibble()

# Mean expression (all-array)
me_aa <- aa_dat %>%
  dplyr::mutate(Subtype = paste0("me_", Subtype)) %>%
  dplyr::group_by(Gene, Subtype) %>%
  dplyr::summarize(Mean_Expression = mean(Expression)) %>%
  tidyr::spread(key = Subtype, value = Mean_Expression)

# Number of cases and top genes (all-array)
n_cases_aa <- dplyr::n_distinct(aa_dat[["sample"]])
n_tp_aa <- dplyr::n_distinct(aa_dat[["Gene"]])

# Pairwise p-values (all-array)
pp_aa <- ggpubr::compare_means(
  formula = Expression ~ Subtype,
  data = aa_dat,
  method = "t.test",
  group.by = "Gene",
  p.adjust.method = "fdr"
) %>%
  dplyr::inner_join(me_aa, by = "Gene") %>%
  dplyr::select(-.y.) %>%
  dplyr::mutate(p.adj = p.adjust(p, method = "fdr"))
readr::write_csv(pp_aa, file.path(params$outputDir, "supplementary/tables/aa_pairwise_pvals.csv"))

# Largest global p-value (all-array)
max_gp_aa <- ggpubr::compare_means(
  formula = Expression ~ Subtype,
  data = aa_dat,
  method = "anova",
  group.by = "Gene"
) %>%
  dplyr::top_n(n = 1, wt = p) %>%
  dplyr::pull("p.format")

# Gene expression for top genes by predicted final subtype (all-array)
# p_aa <- ggboxplot(aa_dat, x = "Subtype", y = "Expression", fill = "Subtype", facet.by = "Gene", nrow = 5, ncol = 11) +
#   stat_compare_means(method = "anova") +
p_aa <- ggplot(aa_dat, aes(x = Subtype, y = Expression, fill = Subtype)) +
  geom_boxplot() +
  facet_wrap(facets = vars(Gene), nrow = 5, ncol = 11) +
  labs(
    x = "Subtype",
    y = "Expression",
    title = paste0("Full All-Array Gene Expression for Top ", n_tp_aa,
                   " Genes by Subtype"),
    subtitle = paste0("(n=", n_cases_aa, ")"),
    caption = paste("Largest global ANOVA p-value", max_gp_aa)
  ) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90))
# print(p_aa)
ggsave(file.path(fig_path, "boxplot_subtype_aa.pdf"), p_aa, width = 11, height = 11)
```

### NanoString

```{r gene_ex_ns, fig.width=11, fig.height=11}
# Joined data (NanoString)
dat_ns <- raw_ns %>%
  dplyr::rename(ottaID = OTTA.ID) %>% 
  dplyr::filter(!ottaID %in% arl_samples[["OTTA ID"]]) %>%
  dplyr::inner_join(final_preds, by = "ottaID") %>%
  dplyr::select(ottaID, Subtype = final, final_glist_ordered) %>%
  tidyr::gather(key = Gene, value = Expression, -c(1:2), factor_key = TRUE) %>%
  dplyr::mutate(
    Subtype = factor(Subtype, levels = names(table(final_preds[["final"]])))
  )

# Mean expression (NanoString)
me_ns <- dat_ns %>%
  dplyr::mutate(Subtype = paste0("me_", Subtype)) %>%
  dplyr::group_by(Gene, Subtype) %>%
  dplyr::summarize(Mean_Expression = mean(Expression)) %>%
  tidyr::spread(key = Subtype, value = Mean_Expression)

# Number of cases and top genes (NanoString)
n_cases_ns <- dplyr::n_distinct(dat_ns[["ottaID"]])
n_tp_ns <- dplyr::n_distinct(dat_ns[["Gene"]])

# Pairwise p-values (NanoString)
pp_ns <- ggpubr::compare_means(
  formula = Expression ~ Subtype,
  data = dat_ns,
  method = "t.test",
  group.by = "Gene",
  p.adjust.method = "fdr"
) %>%
  dplyr::inner_join(me_ns, by = "Gene") %>%
  dplyr::select(-.y.) %>%
  dplyr::mutate(p.adj = p.adjust(p, method = "fdr"))
readr::write_csv(pp_ns, file.path(params$outputDir, "supplementary/tables/ns_pairwise_pvals.csv"))

# Largest global p-value (NanoString)
max_gp_ns <- ggpubr::compare_means(
  formula = Expression ~ Subtype,
  data = dat_ns,
  method = "anova",
  group.by = "Gene"
) %>%
  dplyr::top_n(n = 1, wt = p) %>%
  dplyr::pull("p.format")

# Gene expression for top genes by predicted final subtype
p_ns <- ggplot(dat_ns, aes(x = Subtype, y = Expression, fill = Subtype)) +
  geom_boxplot(na.rm = TRUE) +
  facet_wrap(facets = vars(Gene), nrow = 5, ncol = 11) +
  labs(
    x = "Subtype",
    y = "Expression",
    title = paste0("Full NanoString Gene Expression for Top ", n_tp_ns,
                   " Genes by Subtype"),
    subtitle = paste0("(n=", n_cases_ns, ")"),
    caption = paste("Largest global ANOVA p-value", max_gp_ns)
  ) +
  ylim(range(aa_dat[["Expression"]])) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90))
# print(p_ns)
ggsave(file.path(fig_path, "boxplot_subtype_ns.pdf"), p_ns, width = 11, height = 11)
```

### TCGA

```{r gene_ex_tcga, fig.width=11, fig.height=11}
# Data and class (TCGA)
raw_tcga <- Biobase::exprs(eset)
class_tcga <- Biobase::pData(eset) %>%
  tibble::rownames_to_column("sample") %>%
  dplyr::select(sample, Subtype = MolSubtype)

# Joined data (TCGA)
dat_tcga <- raw_tcga %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename_at("CD3E", ~ "CD3e") %>% # Capitalize to match
  dplyr::select(intersect(final_glist_ordered, colnames(.))) %>% # Missing CYTIP, CD8A, CD68 so only 52 top genes
  tibble::rownames_to_column("sample") %>%
  # dplyr::filter(sample %in% unlist(purrr::map(mapped_tcga[["Short-ID"]], ~ grep(., sample, value = TRUE)))) %>% # using only TCGA matched to OTTA
  dplyr::inner_join(class_tcga, ., by = "sample") %>%
  dplyr::mutate(Subtype = factor(dplyr::case_when(
    Subtype == "C1" ~ "C1.MES",
    Subtype == "C2" ~ "C2.IMM",
    Subtype == "C4" ~ "C4.DIF",
    Subtype == "C5" ~ "C5.PRO"
  ))) %>%
  tidyr::gather(key = Gene, value = Expression, -c(1:2), factor_key = TRUE) %>%
  tibble::as_tibble()

# Mean expression (TCGA)
me_tcga <- dat_tcga %>%
  dplyr::mutate(Subtype = paste0("me_", Subtype)) %>%
  dplyr::group_by(Gene, Subtype) %>%
  dplyr::summarize(Mean_Expression = mean(Expression)) %>%
  tidyr::spread(key = Subtype, value = Mean_Expression)

# Number of cases and top genes (TCGA)
n_cases_tcga <- dplyr::n_distinct(dat_tcga[["sample"]])
n_tp_tcga <- dplyr::n_distinct(dat_tcga[["Gene"]])

# Pairwise p-values (TCGA)
pp_tcga <- ggpubr::compare_means(
  formula = Expression ~ Subtype,
  data = dat_tcga,
  method = "t.test",
  # method = "wilcox.test", # use for small samples if filtering TCGA by matched OTTA
  group.by = "Gene",
  p.adjust.method = "fdr"
) %>%
  dplyr::inner_join(me_tcga, by = "Gene") %>%
  dplyr::select(-.y.) %>%
  dplyr::mutate(p.adj = p.adjust(p, method = "fdr"))
readr::write_csv(pp_tcga, file.path(params$outputDir, "supplementary/tables/tcga_pairwise_pvals.csv"))

# Largest global p-value (TCGA)
max_gp_tcga <- ggpubr::compare_means(
  formula = Expression ~ Subtype,
  data = dat_tcga,
  method = "anova",
  group.by = "Gene"
) %>%
  dplyr::top_n(n = 1, wt = p) %>%
  dplyr::pull("p.format")

# Gene expression for top genes by predicted final subtype (TCGA)
# p_tcga <- ggboxplot(dat_tcga, x = "Subtype", y = "Expression", fill = "Subtype", facet.by = "Gene", nrow = 5, ncol = 11) +
#   stat_compare_means(method = "anova") +
p_tcga <- ggplot(dat_tcga, aes(x = Subtype, y = Expression, fill = Subtype)) +
  geom_boxplot() +
  facet_wrap(facets = vars(Gene), nrow = 5, ncol = 11) +
  labs(
    x = "Subtype",
    y = "Expression",
    title = paste0("Full TCGA Gene Expression for Top ", n_tp_tcga,
                   " Genes by Subtype"),
    subtitle = paste0("(n=", n_cases_tcga, ")"),
    caption = paste("Largest global ANOVA p-value", max_gp_tcga)
  ) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90))
# print(p_tcga)
ggsave(file.path(fig_path, "boxplot_subtype_tcga.pdf"), p_tcga, width = 11, height = 11)
```
